version: '3.8'

services:
  backend:
    build: ./
    command: gunicorn test_project_store.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
    networks:
      - internal_network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_network
    expose:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/my_site.conf:/etc/nginx/conf.d/my_site.conf:ro
      - ./static:/usr/share/nginx/html/static
      - /dev/null:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - internal_network

volumes:
  postgres_data:

networks:
  internal_network:
    driver: bridge
